import { EventTopic } from '@hrms/contracts';
import { writeAudit, publishEvent, Prisma, type TenantClient } from '@hrms/db';
import { readPolicy } from './policy.ts';
import { assessTrust, haversineMeters, type TrustFlag } from './trust.ts';
import { resolveWorkDate, tenantTimeZone } from './workdate.ts';
import { punchPermissions } from './consent.ts';

/**
 * Recording attendance punches (document 10).
 *
 * The rule that cannot be compromised: **a punch is never refused because its
 * evidence is weak.** It is recorded, scored, and flagged.
 *
 * An employee who genuinely worked but whose phone reports a poor location
 * still worked. Refusing their punch means docking their pay on a signal that
 * may be wrong — and the person who bears that is the one with the least means
 * of arguing back.
 */

export class PunchError extends Error {
  constructor(
    message: string,
    readonly kind: 'not_found' | 'duplicate' | 'locked' | 'blocked',
  ) {
    super(message);
    this.name = 'PunchError';
  }
}

interface PunchBase {
  employeeId: string;
  type: 'IN' | 'OUT' | 'BREAK_START' | 'BREAK_END';
  /** The punch time according to the client. Verified against the server clock. */
  punchedAt: Date;
  latitude?: number | null | undefined;
  longitude?: number | null | undefined;
  accuracyM?: number | null | undefined;
  photoKey?: string | null | undefined;
  mockLocationReported?: boolean | undefined;
  /** Generated by the client before sending. The offline queue's idempotency key. */
  dedupeKey: string;
  deviceInfo?: string | null | undefined;
  ip?: string | null | undefined;
}

/**
 * A manual entry must carry its reason, and the type enforces that.
 *
 * The reason is not data tidiness. A manual punch is the only path where an
 * attendance record appears without the presence of the person concerned —
 * no location, no photo, none of their device. When a wage dispute arrives, what
 * decides it is not the trust score but whether there is a sentence explaining
 * why that row exists. An optional column is how that sentence goes missing on
 * precisely the rows that need it most.
 */
export type PunchInput = PunchBase &
  (
    | { source: 'WEB' | 'MOBILE' | 'DEVICE'; manualReason?: undefined }
    | { source: 'MANUAL'; manualReason: string }
  );

export interface PunchResult {
  id: string;
  workDate: string;
  trustScore: number;
  flags: TrustFlag[];
  needsReview: boolean;
  /** True when this punch was already recorded (an offline resend). */
  duplicate: boolean;
}

export async function recordPunch(
  tx: TenantClient,
  tenantId: string,
  input: PunchInput,
  actorUserId: string,
): Promise<PunchResult> {
  const employee = await tx.employee.findFirst({
    where: { id: input.employeeId, tenantId },
    select: { id: true },
  });
  if (!employee) throw new PunchError('Karyawan tidak ditemukan', 'not_found');

  const timeZone = await tenantTimeZone(tx, tenantId);

  /**
   * Consent is checked on the SERVER, not only on screen (P9).
   *
   * The attendance screen does hide the camera button when photo consent has
   * been withdrawn — but a screen can be replaced, and the person who bears
   * that is the one who believed their request was honoured. Coordinates and
   * photos sent without consent are discarded here, before touching the database.
   *
   * Attendance machine punches and HR entries carry neither, so there is nothing
   * to check for them.
   */
  const consent =
    input.source === 'WEB' || input.source === 'MOBILE'
      ? await punchPermissions(tx, tenantId, input.employeeId)
      : { location: true, photo: true, pending: [] };

  const latitude = consent.location ? (input.latitude ?? null) : null;
  const longitude = consent.location ? (input.longitude ?? null) : null;
  const accuracyM = consent.location ? (input.accuracyM ?? null) : null;
  const photoKey = consent.photo ? (input.photoKey ?? null) : null;

  // A resend is checked BEFORE inserting, not caught afterwards.
  //
  // The first version relied on the unique constraint and then recovered in a
  // catch block. That does not work in PostgreSQL: once a statement fails inside
  // a transaction, the transaction enters an aborted state and EVERY subsequent
  // query fails with it — including the query meant to fetch the existing row.
  // The result was a 500, when all that happened was the offline queue resending
  // a punch that had already been stored.
  //
  // The unique constraint is still there and still the real guarantee; what
  // changed is only that the ordinary path no longer runs through an error.
  /**
   * The dedupe key is mandatory, and checked at runtime even though the type
   * already requires it.
   *
   * `where: { dedupeKey: undefined }` in Prisma **ignores the condition** — it
   * does not look for a row with a null key, it matches any row in that tenant.
   * A punch arriving without a key would therefore be answered "already
   * recorded" along with somebody else's trust score, and not one new row would
   * be stored.
   *
   * TypeScript already prevents this in every existing caller. This guard is for
   * what TypeScript does not see: a JSON body that passes validation because its
   * schema is loosened later, and calls from a file run with transform-types —
   * which strips the types without checking them.
   *
   * Found through exactly such a file: a verification script that forgot to
   * include the key received "duplicate" for every punch, and for several
   * minutes the result read like a tenant policy that did not work.
   */
  if (!input.dedupeKey) {
    throw new PunchError('Ketukan tanpa kunci dedupe tidak dapat diproses', 'not_found');
  }

  const alreadyRecorded = await tx.punchLog.findFirst({
    where: { tenantId, dedupeKey: input.dedupeKey },
    select: { id: true, workDate: true, trustScore: true, review: true, trustFlags: true },
  });

  if (alreadyRecorded) {
    return {
      id: alreadyRecorded.id,
      workDate: alreadyRecorded.workDate.toISOString().slice(0, 10),
      trustScore: alreadyRecorded.trustScore,
      flags: (alreadyRecorded.trustFlags as TrustFlag[] | null) ?? [],
      needsReview: alreadyRecorded.review === 'NEEDS_REVIEW',
      duplicate: true,
    };
  }

  // --- The nearest work site --------------------------------------------------
  let workSiteId: string | null = null;
  let distanceM: number | null = null;
  let radiusM: number | null = null;
  let maxAccuracyM: number | null = null;

  if (latitude != null && longitude != null) {
    const sites = await tx.workSite.findMany({
      where: { tenantId, isActive: true },
      select: {
        id: true,
        latitude: true,
        longitude: true,
        radiusM: true,
        maxAccuracyM: true,
      },
    });

    // The NEAREST site, not the first match. A company with several branches
    // close together would have "first match" pick the wrong branch, and the
    // per-site recap becomes meaningless.
    for (const site of sites) {
      const d = haversineMeters(
        { lat: latitude, lon: longitude },
        { lat: Number(site.latitude), lon: Number(site.longitude) },
      );
      if (distanceM === null || d < distanceM) {
        distanceM = d;
        workSiteId = site.id;
        radiusM = site.radiusM;
        maxAccuracyM = site.maxAccuracyM;
      }
    }
  }

  // --- A period that is already closed ----------------------------------------
  //
  // Only a manual entry is refused here, and that distinction is deliberate.
  //
  // A WEB punch arriving late — an offline queue that only reconnects after the
  // period was closed — is still recorded. Its row is harmless: `persistDay`
  // refuses to update a locked day, so the figure payroll uses does not move.
  // Refusing the punch would instead throw away the only evidence that the
  // person was there.
  //
  // A manual entry is different because its intent is different. HR enters it
  // PRECISELY to change the figure, and that figure will not change. Letting it
  // "succeed" means HR believes their correction is done while the payslip stays
  // wrong — a failure only discovered when the employee complains.
  if (input.source === 'MANUAL') {
    const workDateForLock = resolveWorkDate(input.punchedAt, timeZone);
    const closed = await tx.attendancePeriod.findFirst({
      where: {
        tenantId,
        closedAt: { not: null },
        startDate: { lte: workDateForLock },
        endDate: { gte: workDateForLock },
      },
      select: { year: true, month: true },
    });

    if (closed) {
      throw new PunchError(
        `Periode ${String(closed.month).padStart(2, '0')}/${closed.year} sudah ditutup. ` +
          'Koreksi pada periode tertutup tidak lagi mengubah angka yang dipakai payroll.',
        'locked',
      );
    }
  }

  // --- Tenant policy ------------------------------------------------------------
  const policy = await readPolicy(tx, tenantId);

  /**
   * The policy for a denied permission (document 10 §2.4).
   *
   * `BLOCK` means mobile punching is impossible without the required evidence —
   * and the refusal has to name **what is missing and what the way out is**,
   * not merely say "failed". An employee refused at the factory gate at seven in
   * the morning can do nothing with a message that does not tell them where to
   * go.
   *
   * Attendance machine punches and manual HR entries are exempt: by their nature
   * neither carries a location or a photo, and blocking them means switching off
   * the two correction paths that are needed precisely when an employee's phone
   * is the problem.
   */
  if (policy.onPermissionDenied === 'BLOCK' && input.source !== 'DEVICE' && input.source !== 'MANUAL') {
    const kurang: string[] = [];
    if (policy.requireLocation && distanceM === null) kurang.push('lokasi');
    if (policy.requirePhoto && !photoKey) kurang.push('foto');

    if (kurang.length > 0) {
      throw new PunchError(
        `Presensi membutuhkan ${kurang.join(' dan ')}. ` +
          'Aktifkan izinnya di setelan peramban, gunakan mesin absensi, ' +
          'atau minta HR memasukkan koreksi manual.',
        'blocked',
      );
    }
  }

  // --- Trust scoring --------------------------------------------------------
  const serverNow = new Date();
  const clockSkewSeconds = Math.round(
    (input.punchedAt.getTime() - serverNow.getTime()) / 1000,
  );

  const assessment = assessTrust({
    source: input.source,
    distanceM,
    radiusM,
    accuracyM,
    maxAccuracyM,
    hasPhoto: Boolean(photoKey),
    // An offline punch is sent later; a time difference there is normal and not
    // a signal. Only a punch sent immediately is scored on it.
    clockSkewSeconds: input.source === 'DEVICE' ? null : clockSkewSeconds,
    mockLocationReported: input.mockLocationReported ?? false,
    consentWithheld: { location: !consent.location, photo: !consent.photo },
    policy: {
      requireLocation: policy.requireLocation,
      requirePhoto: policy.requirePhoto,
      autoApproveThreshold: policy.autoApproveThreshold,
    },
  });

  // --- The working date -------------------------------------------------------
  const workDate = resolveWorkDate(input.punchedAt, timeZone);

  try {
    const punch = await tx.punchLog.create({
      data: {
        tenantId,
        employeeId: input.employeeId,
        type: input.type,
        source: input.source,
        punchedAt: input.punchedAt,
        workDate,
        latitude: latitude != null ? new Prisma.Decimal(latitude) : null,
        longitude: longitude != null ? new Prisma.Decimal(longitude) : null,
        accuracyM,
        workSiteId,
        distanceM,
        photoKey,
        // Retention comes from tenant policy, not a constant. The figure is
        // computed WHEN STORING, not when deleting — so raising the retention
        // does not extend the life of existing photos, and lowering it does not
        // shorten them. A photo is bound by the promise in force when it was taken.
        photoExpiresAt: photoKey
          ? new Date(Date.now() + policy.photoRetentionDays * 86_400_000)
          : null,
        trustScore: assessment.score,
        trustFlags: assessment.flags.length > 0 ? (assessment.flags as never) : Prisma.DbNull,
        // A manual entry does not enter the review queue, and that is not leniency.
        //
        // It has already been reviewed — by the person who entered it, at the
        // moment they entered it, with the reason recorded on this row. Sending it
        // to the queue means asking HR to review their own work, and meanwhile it
        // raises the flagged ratio: the very metric used to detect a badly set
        // trust threshold would lie in proportion to how diligently HR corrects
        // things.
        //
        // Its score STAYS low and stays visible. The evidence genuinely is weak,
        // and raising the score would hide something true.
        ...(input.source === 'MANUAL'
          ? {
              review: 'APPROVED' as const,
              reviewedBy: actorUserId,
              reviewedAt: new Date(),
              reviewNote: input.manualReason,
            }
          : { review: assessment.needsReview ? ('NEEDS_REVIEW' as const) : ('ACCEPTED' as const) }),
        dedupeKey: input.dedupeKey,
        deviceInfo: input.deviceInfo ?? null,
        ip: input.ip ?? null,
      },
      select: { id: true },
    });

    // A manual entry is ALWAYS audited, whatever its score.
    //
    // This is the highest-risk path in the attendance module: HR punches on
    // someone else's behalf, with no location, no photo, and without the person
    // concerned being present. Its trust score is already low, but a score only
    // triggers a review — what a dispute needs is a record of who entered it and
    // when.
    if (input.source === "MANUAL") {
      await writeAudit(tx, tenantId, {
        action: "attendance.punch.manual_entry",
        entityType: "punch_log",
        entityId: punch.id,
        actorUserId,
        after: {
          employeeId: input.employeeId,
          type: input.type,
          punchedAt: input.punchedAt.toISOString(),
          reason: input.manualReason,
        },
        ip: input.ip ?? undefined,
      });
    }

    if (assessment.needsReview && input.source !== 'MANUAL') {
      await publishEvent(tx, tenantId, {
        topic: EventTopic.PUNCH_FLAGGED,
        payload: {
          tenantId,
          punchId: punch.id,
          employeeId: input.employeeId,
          trustScore: assessment.score,
          flags: assessment.flags.map((f) => f.code),
        },
      });
    }

    return {
      id: punch.id,
      workDate: workDate.toISOString().slice(0, 10),
      trustScore: assessment.score,
      flags: assessment.flags,
      needsReview: assessment.needsReview && input.source !== 'MANUAL',
      duplicate: false,
    };
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
      // Two submissions arrived at genuinely the same moment and both passed the
      // checks above. The unique constraint refuses the second, and that is the
      // right behaviour — exactly one row is stored.
      //
      // This transaction is already aborted, so nothing more can be read here.
      // The caller translates it into a success response: from the client's point
      // of view, its punch really was recorded.
      throw new PunchError(
        'Presensi ini sudah tercatat',
        'duplicate',
      );
    }
    throw error;
  }
}
export interface ReviewDecision {
  punchId: string;
  approve: boolean;
  note: string;
}

/**
 * Reviewing a flagged punch.
 *
 * The HR decision is recorded with its reason, and `trustScore` is not changed.
 * A score is the machine's assessment of the evidence; a decision is a human's
 * assessment of the context. Overwriting the first with the second erases why
 * the punch was flagged — and that is exactly what is needed when the same
 * pattern recurs next month.
 */
export async function reviewPunch(
  tx: TenantClient,
  tenantId: string,
  decision: ReviewDecision,
  actorUserId: string,
): Promise<void> {
  const punch = await tx.punchLog.findFirst({
    where: { id: decision.punchId, tenantId },
    select: { id: true, review: true, employeeId: true },
  });
  if (!punch) throw new PunchError('Data presensi tidak ditemukan', 'not_found');

  await tx.punchLog.update({
    where: { id: decision.punchId },
    data: {
      review: decision.approve ? 'APPROVED' : 'REJECTED',
      reviewedBy: actorUserId,
      reviewedAt: new Date(),
      reviewNote: decision.note.trim(),
    },
  });

  await writeAudit(tx, tenantId, {
    action: decision.approve ? 'attendance.punch.approved' : 'attendance.punch.rejected',
    entityType: 'punch_log',
    entityId: decision.punchId,
    actorUserId,
    before: { review: punch.review },
    after: { review: decision.approve ? 'APPROVED' : 'REJECTED', note: decision.note },
  });
}
